version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run:
          name: Running tests
          command: python test.py
  build:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run:
          name: Running Build
          command: python build.py
  deploy:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run:
          name: deploy
          command: python deploy.py

workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
  
  schedule-workflow:
    triggers:
      - schedule:
          cron: "*/30 * * * *"
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - test
